sudo: required
services:
    - docker

before_install:
    - docker build -e CI=true -t laudes/docker-react -f Dockerfile.dev .

script:
    - docker run laudes/docker-react npm run test -- --coverage